baseURL = "https://irina-portfolio-site.pages.dev/"
languageCode = "zh-CN"
title = "Irina Jiang"
theme = "PaperMod"

[params]
  description = "热爱人类学的中文系学生,喜欢旅行,摄影,运动和写作. The world is my oyster."
  author = "Irina Jiang"
